config/routes.rb
Rails.application.routes.draw do
  # トップページのルート設定
  root 'static_pages#top'

  # ユーザー登録関連のルート設定
  resources :users, only: [:new, :create]
  
  # ユーザーセッション（ログイン・ログアウト）関連のルート設定
  resources :user_sessions, only: [:new, :create, :destroy]

  # ログイン画面へのルート設定
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'

  # ログアウト処理へのルート設定
  post 'logout', to: 'user_sessions#destroy'
  delete 'logout', to: 'user_sessions#destroy'

  get "up" => "rails/health#show", as: :rails_health_check

  resources :boards, only: [:new, :create, :index, :show]

  # コメント処理のルート設定
  resources :boards do
    resources :comments, shallow: true, only: %i[create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/board.rb
class Board < ApplicationRecord
  belongs_to :user
  validates :store_name, presence: true, length: { maximum: 255 }
  validates :product_name, presence: true, length: { maximum: 255 }
  validates :jan_code, presence: true, length: { maximum: 13 }
  validates :expiration_date, presence: true

  has_many :comments, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :board

  validates :body, presence: true, length: { maximum: 65535 }
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  validates :email, uniqueness: true
  validates :email, presence: true
  validates :first_name, presence: true, length: { maximum: 255 }
  
  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  has_many :boards

  has_many :comments, dependent: :destroy

  def own?(comment)
    self.id == comment.user_id
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_login

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def top
    @posts = Post.all
  end

  private

  def require_login
    if current_user.nil?
      flash[:danger] = t('flash.not_authenticated')
      redirect_to login_path
    end
  end

  def set_current_user
    @current_user = current_user.decorate if current_user
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :require_login, only: %i[index new create show]

  def index
    @boards = Board.includes(:user).order(created_at: :desc)
  end

  def new
    @board = Board.new
  end

  def create
    @board = current_user.boards.build(board_params)
    if @board.save
      flash[:success] = t('flash.boards.success', item: Board.model_name.human)
      redirect_to boards_path
    else
      flash[:danger] = t('flash.boards.danger', item: Board.model_name.human)
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @board = Board.find(params[:id])
    @comment = Comment.new
    @store_name = @board.store_name
    @comments = @board.comments.includes(:user).order(created_at: :desc)
  end

  private

  def board_params
    params.require(:board).permit(:store_name, :product_name, :jan_code, :expiration_date)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = current_user.comments.build(comment_params)
    if @comment.save
      flash[:success] = t('comments.comment_success')
      redirect_to board_path(@comment.board)
    else
      flash[:danger] = t('comments.comment_danger')
      @board = Board.find(params[:board_id])
      @comments = @board.comments.includes(:user).order(created_at: :desc) # ここで@commentsをセット
      render 'boards/show', status: :unprocessable_entity
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:body, :board_id).merge(user_id: current_user.id)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  skip_before_action :require_login

  def top
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, only: %i[new create]

  def new; end

  def create
    @user = login(params[:email], params[:password])
    if @user
      flash[:success] = t('user_sessions.create.login_success')
      redirect_to boards_path
    else
      flash[:danger] = t('user_sessions.create.login_failure')
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    logout
    flash[:success] = t('user_sessions.logout_success')
    redirect_to root_path, status: :see_other
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: %i[new create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = t('users.new.success')
      redirect_to root_path
    else
      flash[:danger] = t('users.new.danger')
      render :new, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :first_name, :last_name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/boards/_board.html.erb
<div class="col-sm-12 col-lg-4 mb-3">
  <div id="board-id-<%= board.id %>">
    <div class="card">
      <div class="card-body">
        <div class="d-flex">
          <h4 class="card-title">
            <%= link_to board.store_name, board_path(board) %>
          </h4>
          <div class='ms-auto'>
            <%= link_to '#', id: 'button-edit-#{board.id}' do %>
              <i class="bi bi-pencil-fill"></i>
            <% end %>
            <%= link_to '#', id: 'button-delete-#{board.id}', method: :delete, data: {confirm: ''} do %>
              <i class="bi bi-trash-fill"></i>
            <% end %>
          </div>
        </div>
        <ul class="list-inline">
          <li><i class="bi bi-box"></i>商品名: <%= board.product_name %></li>
          <li><i class="bi bi-upc-scan"></i>JANコード: <%= board.jan_code %></li>
          <li><i class="bi bi-calendar"></i>期限日: <%= board.expiration_date %></li>
          <li><i class="bi bi-person"></i><%= board.user.decorate.full_name %></li>
          <li><i class="bi bi-calendar"></i><%= l board.created_at, format: :short %></li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/boards/index.html.erb
<div class="container pt-3">
  <div class="row">
    <div class="col-lg-10 offset-lg-1">
      <!-- 検索フォーム -->
      <form>
        <div class="input-group mb-3">
          <input class="form-control" placeholder="検索ワード" type="search" />
          <div class="input-group-append">
            <input type="submit" value="検索" class="btn btn-primary" />
          </div>
        </div>
      </form>
    </div>
  </div>
  <!-- 掲示板一覧 -->
  <div class="row">
    <div class="col-12">
      <div class="row">
        <% if @boards.present? %>
          <%= render @boards %>
        <% else %>
          <div class="mb-3">掲示板がありません</div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/boards/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-8 offset-lg-2">
      <h1>期限チェックリスト作成</h1>
      <!-- ここからform_withを使う形に修正してください -->
      <%= form_with(model: @board, local: true, class: "new_board") do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        <div class="mb-3">
          <%= f.label :store_name, "店名" %>
          <%= f.text_field :store_name, id: "boards.store_name", class: "form-control" %>
        </div>
        <div class="mb-3">
          <%= f.label :product_name, "商品名" %>
          <%= f.text_field :product_name, id: "board_product_name", class: "form-control" %>
        </div>
        <div class="mb-3">
          <%= f.label :jan_code, "JANコード" %>
          <%= f.text_field :jan_code, id: "board_jan_code", class: "form-control" %>
        </div>
        <div class="mb-3">
          <%= f.label :expiration_date, "期限日" %>
          <%= f.text_field :expiration_date, id: "board_expiration_date", class: "form-control" %>
        </div>
        <%= f.submit "登録", class: "btn btn-primary", data: { disable_with: "登録中..." } %>
      <% end %>
      <!-- ここまでform_withを使う形に修正してください -->
    </div>
  </div>
</div>

app/views/boards/show.html.erb
<div class="container pt-5">
  <div class="row mb-3">
    <div class="col-lg-8 offset-lg-2">
      <h1><%= t('.title') %></h1>
      <article class="card">
        <div class="card-body">
          <div class="row">
            <div class="col-md-9">
              <h3 style="display: inline;"><%= @store_name %></h3>
              <ul class="list-inline">
                <li class="list-inline-item"><%= "by #{@board.user.decorate.full_name}" %></li>
                <li class="list-inline-item"><%= l @board.created_at, format: :long %></li>
              </ul>
              <div class='d-flex justify-content-end'>
                <%= link_to "#", id: "button-edit-#{@board.id}" do %>
                  <i class='bi bi-pencil-fill'></i>
                <% end %>
                <%= link_to "#", id: "button-delete-#{@board.id}", class: "ms-2" do %>
                  <i class="bi bi-trash-fill"></i>
                <% end %>
              </div>
            </div>
          </div>
          <p>
            商品名: <%= @board.product_name %><br>
            JANコード: <%= @board.jan_code %><br>
            期限日: <%= l @board.expiration_date, format: :long %>
          </p>
        </div>
      </article>
    </div>
  </div>
  <!-- コメントフォーム -->
  <%= render 'comments/form', comment: @comment, board: @board %> 
  <div class="row">
    <div class="col-lg-8 offset-lg-2">
      <table class="table">
        <tbody id="table-comment">
          <!-- コメントエリア -->
          <%= render @comments %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/comments/_comment.html.erb
<tr id="comment-<%= comment.id %>">
  <td style="width: 60px">
    <%= image_tag 'sample.jpg', width: "50", height: "50", class: "rounded-circle" %>
  </td>
  <td>
    <h3 class="small"><%= comment.user.decorate.full_name %></h3>
    <p><%= simple_format(comment.body) %></p>
  </td>
  <% if current_user.own?(comment) %>
    <td class="action">
      <ul class="list-inline justify-content-center" style="float: right;">
        <li class="list-inline-item">
          <%= link_to "#", class: "edit-comment-link" do %>
            <i class="bi bi-pencil-fill"></i>
          <% end %>
        </li>
        <li class="list-inline-item">
          <%= link_to "#", class: "delete-comment-link" do %>
            <i class="bi bi-trash-fill"></i>
          <% end %>
        </li>
      </ul>
    </td>
  <% end %>
</tr>

app/views/comments/_form.html.erb
<div class="row mb-3" id="comment-form">
  <div class="col-lg-8 offset-lg-2">
    <%= form_with model: comment, url: board_comments_path(board) do |f| %>
      <%= f.hidden_field :board_id, value: board.id %>
      <%= f.label :body %>
      <%= f.text_area :body, class: "form-control mb-3", row: "4", placeholder: Comment.human_attribute_name(:body) %>
      <%= f.submit t('defaults.post'), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BATTLE OF RUNTEQ</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <%= render 'shared/flash_message' %> 
    <% if logged_in? %>
      <%= render 'shared/header' %>
    <% else %>
      <%= render 'shared/before_login_header' %>
    <% end %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/shared/_before_login_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navigation navbar-light bg-light">
    <%= link_to root_path, class: 'navbar-brand' do %>
      <%= image_tag 'logo.png' %>
    <% end %>
    <button class='navbar-toggler' data-bs-toggle='collapse' data-bs-target='#navbarSupportedContent'
      aria-controls='navbarSupportedContent' aria-expanded='false' aria-label='Toggle navigation'>
      <span class='navbar-toggler-icon'></span>
    </button>

    <div class='collapse navbar-collapse' id='navbarSupportedContent'>
      <ul class='navbar-nav ms-auto main-nav align-items-center'>
        <li class="nav-item">
          <%= link_to t('header.login'), login_path ,class: 'nav-link' %>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <ul class="mb-0">
      <% object.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>">
    <%= message %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer id='footer' class='footer-bottom'>
  <div class='container'>
    <div class='row'>
      <div class='col-sm-6 col-12'>
        <div class='copyright'>
          <p>2024. BATTLE OF RUNTEQ vol.5</p>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header>
  <nav class='navbar navbar-expand-lg navigation navbar-light bg-light'>
    <%= link_to('/', class: 'navbar-brand') do %>
      <%= image_tag('logo.png') %>
    <% end %>
    <button class='navbar-toggler' data-bs-toggle='collapse' data-bs-target='#navbarSupportedContent'
      aria-controls='navbarSupportedContent' aria-expanded='false' aria-label='Toggle navigation'>
      <span class='navbar-toggler-icon'></span>
    </button>

    <div class='collapse navbar-collapse' id='navbarSupportedContent'>
      <ul class='navbar-nav ms-auto main-nav align-items-center'>
        <li class='nav-item dropdown dropdown-slide'>
          <%= link_to('#', class: 'nav-link dropdown-toggle', data: { bs_toggle: 'dropdown' }, aria: { haspopup: 'true', expanded: 'false' }) do %>
            期限チェック
          <% end %>
          <div class='dropdown-menu dropdown-menu-end'>
            <%= link_to t('header.board_index'), boards_path, class: 'dropdown-item' %>
            <%= link_to t('header.create_board'), new_board_path, class: 'dropdown-item' %>
          </div>
        </li>

        <li class='nav-item'>
          <%= link_to('#', class: 'nav-link') do %>
            ブックマーク
          <% end %>
        </li>

        <li class='nav-item dropdown dropdown-slide'>
          <%= link_to('#', class: 'nav-link', data: { bs_toggle: 'dropdown' }, aria: { haspopup: 'true', expanded: 'false' }, id: 'header-profile') do %>
            <%= image_tag('sample.jpg', class: 'rounded-circle mr15', width: '40', height: '40') %>
          <% end %>
          <div class='dropdown-menu dropdown-menu-end'>
            <div class='dropdown-item'><%= current_user.decorate.full_name %></div>
            <div class='dropdown-divider'></div>
            <%= link_to('#', class: 'dropdown-item') do %>
              プロフィール
            <% end %>
            <%= link_to t('header.logout'), logout_path, class: 'dropdown-item', data: { turbo_method: :delete } %>
          </div>
        </li>

        <% if current_user %>
          <span><%= current_user.decorate.full_name %></span>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/static_pages/top.html.erb
<div class='top-wrapper'>
  <div class='top-inner-text'>
    <h1>BATTLE OF RUNTEQ</h1>
  </div>
</div>

app/views/user_sessions/create.html.erb
<h1>UserSessions#create</h1>
<p>Find me in app/views/user_sessions/create.html.erb</p>

app/views/user_sessions/destroy.html.erb
<h1>UserSessions#destroy</h1>
<p>Find me in app/views/user_sessions/destroy.html.erb</p>

app/views/user_sessions/new.html.erb
<div class="container">
  <div class="row">
    <div class=" col-md-10 offset-md-1 col-lg-8 offset-lg-2">
      <h1><%= t('user_sessions.new.title')%></h1>
      <%= form_with url: login_path do |f| %>
        <div class="form-group">
          <%= f.label :email %>
          <%= f.text_field :email, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :password %>
          <%= f.password_field :password, class: 'form-control' %>
        </div>
        <div style="margin-bottom: 15px;"></div> <!-- スペースを追加するための空のdiv要素 -->
        <div class="actions">
          <%= f.submit t('user_sessions.new.login'), class: 'btn btn-primary' %>
        </div>
      <% end %>
      <div class='text-center'>
        <%= link_to t('user_sessions.new.to_register_page'), new_user_path %>
        <%= link_to t('user_sessions.new.password_forget'), '#' %>
      </div>
    </div>
  </div>
</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 col-lg-8 mx-auto">
      <h1><%= t('users.new.title')%></h1>
      
      <%= form_with model: @user, local: true do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        <div class="mb-3">
          <%= f.label :last_name, class: "form-label" %>
          <%= f.text_field :last_name, class: "form-control", id: "user_last_name" %>
        </div>
        <div class="mb-3">
          <%= f.label :first_name, class: "form-label" %>
          <%= f.text_field :first_name, class: "form-control", id: "user_first_name" %>
        </div>
        <div class="mb-3">
          <%= f.label :email, class: "form-label" %>
          <%= f.email_field :email, class: "form-control", id: "user_email" %>
        </div>
        <div class="mb-3">
          <%= f.label :password, class: "form-label" %>
          <%= f.password_field :password, class: "form-control", id: "user_password" %>
        </div>
        <div class="mb-3">
          <%= f.label :password_confirmation, class: "form-label" %>
          <%= f.password_field :password_confirmation, class: "form-control", id: "user_password_confirmation" %>
        </div>
        <%= f.submit t('helpers.submit.create'), class: "btn btn-primary", "data-disable-with" => t('helpers.submit.create') %>
      <% end %>

      <div class='text-center'>
        <a href="#"><%=t('users.new.to_login_page') %></a>
      </div>
    </div>
  </div>
</div>